### ISSUE TITLE
my testing user is missing some corpora

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#1833]
My test user (nemo814) seems to have "lost" some corpora. (at least) two corpora are not showing up in the corpora list. When nemo814 tries to login to the Prototype app, it keeps asking the password, maybe because the URL is pointing to the corpus which is missing in the corpora list. 

nemo814's corpora list, McGillTemplate2014FallTesting and SpreadsheetTesting_Migmaq are missing
![screen shot 2015-01-23 at 9 29 15 am](https://cloud.githubusercontent.com/assets/760694/5876423/fcf1ed38-a2e4-11e4-9287-24e5803ec9b3.png)

Prototype keeps asking password
![screen shot 2015-01-23 at 9 28 21 am](https://cloud.githubusercontent.com/assets/760694/5876429/13c9862e-a2e5-11e4-8d7a-de314e86aa37.png)

Prototype console
![screen shot 2015-01-23 at 9 28 53 am](https://cloud.githubusercontent.com/assets/760694/5876442/2814c4d6-a2e5-11e4-90e4-6800af116668.png)

**Comment by cesine** [comment]
i looked at your test user's permissions 

```
{
   "_id": "org.couchdb.user:nemo814",
   "_rev": "25-4bcdc81a211ae559cb8d21440fe1f28f",
   "password_scheme": "pbkdf2",
   "iterations": 10,
   "name": "nemo814",
   "roles": [
       "elisedemo-firstcorpus_commenter",
       "elisedemo-firstcorpus_reader",
       "elisedemo-firstcorpus_writer",
       "fielddbuser",
       "jessica-mi_gmaq_group_commenter",
       "jessica-mi_gmaq_group_reader",
       "jessica-mi_gmaq_group_writer",
       "nemo33-malayalam_field_methods_reader",
       "nemo33-malayalam_field_methods_commenter"
   ],
   "type": "user",
   "derived_key": "25d69e6aace0f5f2b5e4472e3c465e9bd78ef12b",
   "salt": "933d5730c984b2ab5d9a404864cfa4fd"
}
```

`(at least) two corpora are not showing up in the corpora list`
* yes, your testing user is missing access to these corpora. are you sure you didn't test permissions on these corpora and then not be able to use them anymore? a while ago we were testing removing ourselves as an admin on a corpus... :)

`because the URL is pointing to the corpus which is missing in the corpora list` 
* yes this is why, because you are trying to login to a corpus that you don't have access to, maybe we can think about communicating this with the user instead since we do get a specific forbidden message, not a you are not connected message. we dont really want to update the prototype anymore though, so this should go in the commonjs library instead so taht it can be used by dative

It looks nothing is broken, someone removed your permissions on some of your corpora. If users do this to each other, we dont really plan on telling them that someone removed them. (like un-friending someone on facebook, we wont tell you if you are removed)
* we will just restore your testing user's permissions to the defaults ;)

**Comment by hisakonog** [comment]
@cesine thanks for checking.  When I started testing for the new release I had access to all corpora, but at some point (I don't remember exactly when) I noticed that hum I might be missing some databases. So it happened not when we were testing removing ourselves, but more recently when we were testing for the new release.  
I am pretty sure I didn't test the permissions of admin users with those corpora that went missing. I never opened "data entry tutorial" in the first place, and I wouldn't mess up with spreadsheettesting_migmaq" admin as I know this database contains actual data that I NEED for purposes other than testing the app. I do remember playing with the permission for malayalam corpus, but the corpus didn't go missing. 
Looks like the corpora I lost access to were those that I had/have the admin access.

**Comment by cesine** [comment]
@hisakonog  which corpora are showing underscores in their names? i repaired my testing user's corpora a while ago, we should repair yours too.

**Comment by hisakonog** [comment]
@cesine  the only corpus that has underscore is nemo33's testing corpus "nemo33-testing_corpus"

**Comment by hisakonog** [comment]
When I was testing with nemo33 for Richard's problem a week ago, I saw strange behaviour in Prototype. Prototype has been updated (Feb 11) so I wanted to see if the app still behaves weird. As of now I have following issues: 

- nemo33 can not logout when he is in Malayalam corpus.  The pop-up "You have to back up your preference... ...make sure it's you" doesn't show up. 

![nemo33unabletologoutmalayalam2](https://cloud.githubusercontent.com/assets/760694/6156357/96662778-b207-11e4-911b-d08d6c1370cb.png)

when I scrolled up a bit there is an error before loading objects, but it seems to be a normal error as other corpora show the same error.  

![screen shot 2015-02-11 at 16 10 29](https://cloud.githubusercontent.com/assets/760694/6156482/a42455aa-b208-11e4-81d9-fc1776a166ba.png)

**Comment by hisakonog** [comment]
- nemo33 can't view "nemo814-SpreadSheetTesting Migmaq".  nemo33 has ReadOnly permission to this corpus. 
![nemo814-spreadsheettesting_migmaqunviewable](https://cloud.githubusercontent.com/assets/760694/6156835/dc76fcc6-b20a-11e4-891d-bf06f55131a3.png)

nemo33 is able to log out while in this corpus, but when he tries to re-login to Prototype, the pop-up "We need to make sure it's you" shows up. When he types his password, the same pop-up shows up ad infinitum. If he clicks "Yep it's me" WITHOUT password, the app lets him in. (I send you the video how this is happening). Also, the URL mysteriously goes to "computationalfieldworkshop-group_data_entry_tutorial"  

nemo33 is missing "computationalfieldworkshop..." corpus in his corpora list on the Spreadsheet app.
