### ISSUE TITLE
Expanding datums reloaded different session

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#1838]
Just as a record: Yuliya had a strange problem. 
When she expanded a datum in some session, the online app reloaded with a different session. When she cleared the browser cache, the problem solved.  
It happened with the session she imported using Prototype. I never experiences this, and I have no session/corpus created via import. I don't know if this has something to do with imported data.

**Comment by hisakonog** [comment]
maybe related to #1829 ?

**Comment by cesine** [comment]
actually its probably related to #1839 the spreadsheet app assumed that datum have a both a sesssion and a sessionID on them, which isnt going to happen if the datum come from another app. when i did the refactor in the last release there was one of the SessionID missing so it made odd behavior. instead, the last release (currentingly in appdev) uses session._id rather than a additional field.
