### ISSUE TITLE
Can't access my field methods corpus

### ISSUE THREAD

**Issue by rjcompton** [OpenSourceFieldlinguistics/FieldDB#1846]
There's something wrong my field methods corpus "rcompton-analyse_avec_informateur_-_hiver_2015". It takes longer to appear in my list of corpora in the chrome app and when it does appear a few seconds later than the others, it won't open. My students can't get access either. (Also, there are underscores between the words in the corpus title that I don't think were there before.)

**Comment by hisakonog** [comment]
Thanks @rjcompton I tested with my user and the corpus that has the newly-appeared underscore in the title doesn't open. @cesine does this have anything to do with the font change when the app was updated?

**Comment by hisakonog** [comment]
To be more specific, when I click the corpus with _ , left to the "logout" button shows "All sessions", so the app seems to recognize it.

**Comment by hisakonog** [comment]
Console doesn't show apparent errors...

![screen shot 2015-02-05 at 11 35 24 pm](https://cloud.githubusercontent.com/assets/760694/6074588/cb3fa0e0-ad8f-11e4-8df4-7d3596288c98.png)

**Comment by rjcompton** [comment]
It started midterm Wednesday. The morning class was fine but when I tried to access LingSync in the afternoon I couldn’t get in.

Best,
R.

**Comment by hisakonog** [comment]
Alan used the app in his class Wednesday afternoon with no problem, so this seems to be a corpus-specific (namely with _ in title) problem not app-general. I am able to access corpora that have no underscore in their titles.

**Comment by cesine** [comment]
@hisakonog  and @rjcompton  i will work on this now

**Comment by rjcompton** [comment]
Thanks :-)

Heading to bed.

Best,
Richard

**Comment by cesine** [comment]
Thus far I have found that the server is unable to reply to the request specifically for richard's corpus details (this is why you see the corpus identifier, with underscores rather than spaces). The error message says that indexing the database has exceed the current memory limits permitted for our couchdb, which is strange because the document is not very big.

```javascript
GET https://corpus.example.org/username-dbname-_hiver_2015/_design/pages/_view/private_corpuses 500 (Internal Server Error)


$ curl https://corpus.example.org/username-dbname-_hiver_2015/_design/pages/_view/private_corpuses {"error":"os_process_error","reason":"OS process timed out."}
```

The suggested solutoin is to upgrade couch and increase the stack size.
http://stackoverflow.com/questions/21273736/couchdb-views-os-process-error-big-documents


We will be upgrading couch soon, but as a short term solution we should find the source of this problem. 


* I reduced the modifiedByUsers field in the corpus 768518fbcd331db59d7e25a1e3987e8e, and 
* changed the map reduce, it still wouldnt index. 
*  I removed the index, and re-ran the query, and it still failed. `$ sudo mv  /usr/local/var/lib/couchdb/.username-dbname-_hiver_2015_design . `
* realized that the other map reduces didnt work either, so it was one of the map reduces that was causing the os process to time out. 
* i thought maybe something was wierd about the data, and looked at the word list and found this


```javascript
["'iffit", " 'ivit"]
ID: 407288acbb6dc078665840febbab852f
1
["'iffit", " 'ivit"]
ID: 407288acbb6dc078665840febbab852f
1
["'sila"]
ID: 407288acbb6dc078665840febbb79e25
1
["'sinik"]
ID: 8ced1991e844058a7eb2a8d281c53807
1
["{ɪ", "i}kusik˺"]
ID: b79eb48158757f2759bd4f248dc15985
1
["{ɪ", "i}kusik˺"]
ID: b79eb48158757f2759bd4f248dc15985
1
["{χ", "x}aojemaŋetũ{ŋ", "n}ã"]
ID: 407288acbb6dc078665840febbad8a5a
1
["{χ", "x}aojemaŋetũ{ŋ", "n}ã"]
ID: 407288acbb6dc078665840febbad8a5a
1
["{χ", "x}aojemaŋetũ{ŋ", "n}ã"]
ID: 407288acbb6dc078665840febbad8a5a
1
["a", "ʔ", "t", "ʰ", "aos{i", "ɪ}k"]
ID: 407288acbb6dc078665840febbba68e6
```

**Comment by hisakonog** [comment]
@cesine this sounds strange to me - my user's corpus my that doesn't open is nemo33-testing_corpus which  has no data in it as far as I remember. I tried to access to that corpus from Prototype but I couldn't, it seems I have another issues with Prototype now...

**Comment by cesine** [comment]
@hisakonog  your corpus is a testing corpus, and has a different problem. it has no corpus details in it. 

https://corpusdev.example.org/_utils/database.html?nemo33-testing_corpus/_design/pages/_view/private_corpuses

richard's corpus is returning a very strange error message that we have never seen before.

![screen shot 2015-02-06 at 10 31 09 pm](https://cloud.githubusercontent.com/assets/196199/6081959/e5693362-ae4f-11e4-885d-f83235471707.png)


it has a similar result as yours when you look at it in the app, but the source of the visual result is different, and the solution is also different.

**Comment by hisakonog** [comment]
Ah ok, the solution for Richard has far greater priority then.

**Comment by cesine** [comment]
I'm trying to figure out which data is causing richard's error. I have been able to eliminate the error if the data is roughly 76 items. I will try to see if some of the recent items are causing the problem.
