### ISSUE TITLE
Question about disparities between corpus datumFields and datum datumFields

### ISSUE THREAD

**Issue by jrwdunham** [OpenSourceFieldlinguistics/FieldDB#1866]
Can someone (@cesine) explain to me how a corpus' datumFields array can come to differ from the datumFields arrays of the datums that are a part of that corpus?

The datums in the Inuktitut corpus, for example, have datum fields with labels like "verse" and "orthography". Yet the datum fields array of the corpus itself does not have datum fields with those labels.

**Comment by cesine** [comment]
can you point me to the code that brought you to this question so i can see why you're asking this? btw i have good internet now so we could have scum meetings again, starting today if youre free at the usual time

**Comment by jrwdunham** [comment]
Try inserting a `console.log @model` in `render` of views/form-add-widget and do the same thing in `render` of views/form. In the first case you'll see the default form model, in which case (if you're logged into a FieldDB server and have activated a corpus) `@model.get('datumFields')` will be the `datumFields` array returned by FieldDB for the corpus. In the second case, `@model` will be just a Backbone model set with a FieldDB datum object and `datumFields` will contain a bunch of fields not present in the corpus (in the case of the Inuktitut db, at least).

My assumption is that the corpus settings (i.e., the corpus-wide definition of what the datum fields are) for the Inuktitut db were changed after datums were added with previous corpus settings. Is that what happened?

**Comment by jrwdunham** [comment]
I can meet for scrum today (20 mins). Let me know

**Comment by HughP** [comment]
Just noticing a couple of issues (like this one and #1870 ) mentioning the term 'datum'. I just want to be sure that I am understanding the term's use in this situation. Are you using the term in the GIS sense of datum? http://en.wikipedia.org/wiki/Geodetic_datum . I mean there are other senses of the term, but I am just wondering.

**Comment by jrwdunham** [comment]
In the FieldDB world, a "datum" is the term used to reference what I (in my OLD world) call a "linguistic form", or just a "form". That is, a morpheme, word, phrase, or sentence. I.e., the "currency" or "atom" of linguistic fieldwork.

In the FieldDB web services, "datum" has a technical meaning. It's the particular data structure (representing a linguistic form) that make up corpora in FieldDB corpus web services.

In Dative I have been using the word "form" for "datum".

**Comment by HughP** [comment]
Awesome, thanks... just checking... because I have had to interact with GIS data some in the context of language documentation. It looked like the javascript was called map.js (if I recall correctly), and those two cues together... well I have a clearer picture now.

**Comment by cesine** [comment]
hi @HughP ! your link made me smile, an excellent example of ambiguity. this wikipedia page: http://en.wikipedia.org/wiki/Datum has more possibilities

Datum is just what the `model/class` for `a unit of data` is called in the code, the user interfaces call it different things depending on what kind of user they are for. We do have some jsdocs if you like that kind of thing: http://opensourcefieldlinguistics.github.io/FieldDB/docs/javascript/Datum.html in there you would see that its `a-typically-sized-piece-of-data-in-a-field-linguistics-app`


----
Details

Basically we had problem finding a name for two things
* a unit of data
 * we didnt want to use "record" since it was [ambigous](https://github.com/OpenSourceFieldlinguistics/FieldDB/search?q=record&type=Issues&utf8=%E2%9C%93) with something "recorded" and the verb to "record" audio or video, since audio and video are important in the system, this might confuse the interns who are trying to code the app 
 * we didnt want to use the word "entry" ssince it was [ambigous](https://github.com/OpenSourceFieldlinguistics/FieldDB/search?q=entry&type=Issues&utf8=%E2%9C%93) with any sort of entered data maybe even meaning an entry in an entry (ie a field in a data point)
 * we didnt want to use "form" since it was [ambigous](https://github.com/OpenSourceFieldlinguistics/FieldDB/search?q=form&type=Issues&utf8=%E2%9C%93) with a form we fill out on a website. a data point isnt always in a `<form>` and a typical webform is an ugly user interface of input boxes (nightmares of watching our collegues spend 60 hours a week entering thier data into a file maker pro database), this might confuse the interns who are trying to code the app 
 * So, we settled on the latin singular of data = [datum](https://github.com/OpenSourceFieldlinguistics/FieldDB/search?q=datum&type=Issues&utf8=%E2%9C%93), in a half joking way hoping to never have to use it on the user interface, or if we did, linguists might get the joke. 
* the first line in an IGT 
 * we didnt want to use "transcription" because maybe for some teams, it would be an orthography if the orthography is close enough to IPA and the consultants are entering/cleaning the data
 * we didnt want to use "attestation" #143 because we didnt really like that word, although its accurate
 * we could have called it "Line 1" but we didnt want a space in the label
 * So, we decided `utterance` could be okay since it might try to encourage users to segment their data by utterances or something close to an intonational phrase or sentence which would be better for any sort of plugins that tried to do speech recognition or syntntactic parsing. it can be of any length, as short as a morpheme and as long as a document, we just tried to ecourage users to keep it linguistic chunk which aligned with some level of prosodic boundary


In any case, we realized we werent the only ones with this problem, since we found that almost all the software we surveyed #45 called it different things. Our primary goal was that linguistics students could read the source code, so we decided to use a new/bizzare word that had no other meaning in software or linguistics as the `class` name so that the interns and devs would know when we are talking about the `class`, and find a way that the app's user interfaces could be user friendly, which means users shouldn't be forced to learn new terminology for stuff they already know intuitively, or from a previous similar software. 

We have a library that localizes and/or "contextualizes" the user interface for the user:  
* for kartuli users a `datum` is called ["ფრაზა"](https://github.com/batumi/AndroidSpeechRecognitionTrainer/blob/master/res/values-ka/strings.xml#L6)
* for spanish speakers a `datum` is called ["dato"](https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/api/locales/es/messages.json#L244)
* for language teachers, translators or computational linguists a `datum` is called a ["sentence"](https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/angular_client/modules/core/app/views/datum_language_lesson.html)
* for field lingiusts a `datum` can be called a ["form"](http://online-linguistic-database.readthedocs.org/en/latest/datastructure.html#form) or a ["record"](http://app.lingsync.org/#/faq) (depending on which kind of field linguist they were raised as)
* for psycholingusts and phonologists a `datum` is called ["stimulus"](https://github.com/ProjetDeRechercheSurLecriture/DyslexDisorthGame/blob/master/angular_client/app/views/datum.html) 
* for lexicographers a `datum` can be called an "entry" or "word" or ["morpheme"](https://lexicondev.lingsync.org/)

You might also find the plurals funny. Since at the time, the convention in backbone was to use regular plurals for collections, this meant that `datum PL` was called `datums`  and `corpus PL` were called `corpuses` in the code, but never for the user...

Now that we arent using only backbone, we sometimes use `datums` and sometimes `data` or `datalist` for the plural of datum... in many cases we can follow api plurality, which means that the base name is the plural form: `/data/123-abc-45-6-efg-892` and `/corpora/123-abc-45-6-efg-283`

**Comment by cesine** [comment]
We had better also document the answer which we talked about during scrum.

This is a good example of the open-endedness of fielddb which could shoot us in the foot, if devs are used to SQL or normalized data and assume something which would be logical in most software, like the fields in datum.datumFields are related in one to one way with corpus.datumFields. Fortunately most interns are used to storing data in LaTeX or Word, not in an SQL type of db so this is the first time we have had to clarify this, that I can think of..

How fielddb works:
Apps/plugins/webservices can add whatever they want as a field on a datum, as long as the field has something like this shape. The `json` part is particularly important because the import->export part of fielddb is supposed to be lossless, which means the original source of the data has to be reconstructable so that users can use fielddb to pipe plugins on their data eg ELAN-> FieldDB to do some glossing -> ELAN 
```javascript
{
	id: "uniqueUnabigouslabelForWhatYourFieldIsfor",
	value: "the actual string representation of this field which should be indexed in a search engine, if the field is not encrypted",
	mask: "a mask of the field that i shown to users if the field is encrypted, and indexed in a search engine if the field is encrypted if the search engine is not permitted to index the encrypted value",
	json: {
		an: "arbitrarily",
		deep: ["representation", "content", "of", "the", "field"],
		wth: {
			whatever: {
				metadata: "you",
				want: true
			}
		}
	},
	helpLinguists: "Tell linguists how to use your field.",
	helpDevelopers: "tell other developers how to use your field"
   ...
}

```

Definitions: 
The `datumFields` in a corpus are the curated fields which the corpus team wants to be on new datum, or used for searching/indexing datum by field name.

The `datumFields` on a datum contain the actual information that is in that datum.

Take homes:
From a user's perspective, 
* if you're building a GUI, its important for users to be able to see and/or edit fields which are are listed in the corpus's default fields on an existing datum, regardless of whether that datum was created with that field originally.

From a software perspective, 
* if you write a script or an app that uses a certain field on datum, you need to be prepared that that field might not exist on that datum and create the field if it doesn't exist.
* no matter how hard you try, other devs and future apps will make it impossible for you to store datum in an SQL table where the fields are columns, so don't try it unless you are putting the entire json stringified in one column.


----
Examples: 
The result of this openendedness is that are many possible scenarios where the corpus' `datumFields` and the datum's `datumFields` are disparate:
* all of which might scare an SQL-kinda-guy, 
* but are actually not a problem if you think in Javascript or python Objects, not normalized tables with columns and rows
* all of which are manifested in the current corpora
* There are the same fields in the corpus as in the datum
 * this happens only rarely, and only in a simple corpus where the user knows which fields they want and the fields in the corpus are stable throughout all data entry. I've only seen this in toy or testing corpora.
* There are more fields in a given datum than there are in the corpus' known datumFields
 * this can happen if a datum was created using the spreadsheet app back when the spreadsheet app didn't use the corpus's fields to make a datum, these fields have a help text which says something like it was created in the spreadsheet app. This shouldn't happen anymore in the spreadsheet app as of v2.37 because now the spreadsheet app has a concept of corpus, so the users have to create the field in the corpus before they can add it on a data entry template
 * this can also happen if the datum was cleaned by a bot. for example, i ran a bot on my inuktitut corpus that parsed out the utterance lines to create the verse and chapter fields, but we didn't add those fields to my corpus because we never needed to add them while we were annotating the data
 * these contexts can be periodically fixed by running the `frequent fields` map reduce, and saving the fields that are not on the corpus, on the corpus (although you might find some fields that the user removed from the default list because they didn't want them, so you might frustrate the user)
* there are more fields in the corpus than on a given datum
 * this is the one situation where your GUI has to do something. this can happen if a datum was created before a corpus field was added. in the prototype, we add these fields visually to the datum so that the user can edit these fields on the datum, if they choose

**Comment by jrwdunham** [comment]
In the spirit of friendly debate over linguistic fieldwork database terminology:

- “We didn't want to use "transcription" because maybe for some teams, it would be an orthography if the orthography is close enough to IPA and the consultants are entering/cleaning the data”

  - I think "transcription" is a better label, for the following reasons:

    - an orthographic transcription is still a transcription (so that's not really a valid objection to the term "transcription").
    - utterance implies (or entails) spoken language, which is too restrictive (e.g., it excludes signed languages).
    - it simply IS a transcription, not an utterance; it's some kind of linguistic expression that has been transcribed. An utterance is an action by an individual. A sequence of written characters is a transcription (maybe orthographic, phonetic, phonemic) but a transcription nonetheless.
    - "utterance" is a more appropriate label for the datum as a whole, or at least some types of datums. That is, the various data points (e.g., transcriptions, categorizations, audio/video recordings) all may represent an utterance of a given speaker at a given time. Of course, a datum may also represent something more abstract, e.g., a morpheme which is a generalization drawn from analyzing multiple real-world utterances.

**Comment by jrwdunham** [comment]
lol, well the point is kind of moot anyways since users should be able to label their fields in whatever way they please. The important thing is that we provide useful (and configurable) application logic. Which is what we're doing...

**Comment by cesine** [comment]
yep:) regardless, i sent the change into review, since its painless and i like transcription better too
